% This function converts a structure from plate_meta to a string that is
% describes the experiment. This is handy as a chart title.

% These structures are generated by plate_meta, but are also duplicated in
% metadata.experiments{i}

% info = metadata.experiments{1};
function string = metadata_to_string(info)
names = fieldnames(info);
string = [];
for i=1:length(names)
    value = info.(names{i});
    if isnumeric(value)
        string = [string ' ' names{i} ':' num2str(value)];
    else
        string = [string ' ' names{i} ':' value];
    end
end
string = string(2:end); % deletes leading space