% from triplicates performed on 3 days, extract out one column's data, all
% 18 time traces. file1,2,3 is the data generated by getplatedata.m
function [ods, red, cfp, yfp] = get18traces(file1, file2, file3, column, wcolumn)
wellmap = generateWellMap(8, 12);
datawells = wellmap(2:7, column + 1); 
whitewells = wellmap(2:7, wcolumn + 1);
[ods, red, cfp, yfp] = deal(zeros(25, 18));

for i = 1:6
    [od, flu] = platewellpreprocess(file1, datawells(i), whitewells(i));
    flu = flu ./ od;
    id = i;
    ods(:, id) = od;
    red(:, i) = flu(:, 1);
    cfp(:, i) = flu(:, 2);
    yfp(:, i) = flu(:, 3);
end
for i = 1:6
    [od, flu] = platewellpreprocess(file2, datawells(i), whitewells(i));
    flu = flu ./ od;
    id = 7:12;
    ods(:, id(i)) = od;
    red(:, id(i)) = flu(:, 1);
    cfp(:, id(i)) = flu(:, 2);
    yfp(:, id(i)) = flu(:, 3);
end
for i = 1:6
    [od, flu] = platewellpreprocess(file3, datawells(i), whitewells(i));
    flu = flu ./ od;
    id = 13:18;
    ods(:, id(i)) = od;
    red(:, id(i)) = flu(:, 1);
    cfp(:, id(i)) = flu(:, 2);
    yfp(:, id(i)) = flu(:, 3);
end